#############################################################################
# Makefile for building: libsst_dxf02_lib_d.a
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  sstDxf02Lib.pro
# Template: lib
# Command: /usr/lib/i386-linux-gnu/qt5/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile sstDxf02Lib.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -fPIC -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -fPIC -std=c++0x -Wall -W $(DEFINES)
INCPATH       = -I. -I../dxflib/Header -I../sstLibreCAD2Lib/Header -I../sst_str01_lib/Header -I../sst_misc01_lib/Header -I../sst_rec04_lib/Header -IHeader -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/i386-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sst_dxf02_lib_d1.0.0
DISTDIR = /home/uli-le/Entwicklung/sst_dxf02_lib/.tmp/sst_dxf02_lib_d1.0.0
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sstDxf02Arc.cpp \
		sstDxf02Base.cpp \
		sstDxf02Insert.cpp \
		sstDxf02Read.cpp \
		sstDxf02Block.cpp \
		sstDxf02Layer.cpp \
		sstDxf02Database.cpp \
		sstDxf02EntityType.cpp \
		sstDxf02Write.cpp \
		sstDxf02Main.cpp \
		sstDxf02Vertex.cpp \
		sstDxf02Polyline.cpp \
		sstDxf02Hatch.cpp \
		sstDxf02HatchLoop.cpp \
		sstDxf02HatchEdge.cpp \
		sstDxf02LType.cpp \
		sstDxf02Circle.cpp \
		sstDxf02MText.cpp \
		sstDxf02Text.cpp 
OBJECTS       = sstDxf02Arc.o \
		sstDxf02Base.o \
		sstDxf02Insert.o \
		sstDxf02Read.o \
		sstDxf02Block.o \
		sstDxf02Layer.o \
		sstDxf02Database.o \
		sstDxf02EntityType.o \
		sstDxf02Write.o \
		sstDxf02Main.o \
		sstDxf02Vertex.o \
		sstDxf02Polyline.o \
		sstDxf02Hatch.o \
		sstDxf02HatchLoop.o \
		sstDxf02HatchEdge.o \
		sstDxf02LType.o \
		sstDxf02Circle.o \
		sstDxf02MText.o \
		sstDxf02Text.o
DIST          = /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		sstDxf02Lib.pro ./Header/sstDxf02Lib.h sstDxf02Arc.cpp \
		sstDxf02Base.cpp \
		sstDxf02Insert.cpp \
		sstDxf02Read.cpp \
		sstDxf02Block.cpp \
		sstDxf02Layer.cpp \
		sstDxf02Database.cpp \
		sstDxf02EntityType.cpp \
		sstDxf02Write.cpp \
		sstDxf02Main.cpp \
		sstDxf02Vertex.cpp \
		sstDxf02Polyline.cpp \
		sstDxf02Hatch.cpp \
		sstDxf02HatchLoop.cpp \
		sstDxf02HatchEdge.cpp \
		sstDxf02LType.cpp \
		sstDxf02Circle.cpp \
		sstDxf02MText.cpp \
		sstDxf02Text.cpp
QMAKE_TARGET  = sst_dxf02_lib_d
DESTDIR       = ../libs/#avoid trailing-slash linebreak
TARGET        = libsst_dxf02_lib_d.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

staticlib: ../libs/$(TARGET)

../libs/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d ../libs/ || mkdir -p ../libs/
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)
	-$(DEL_FILE) ../libs/$(TARGET)
	-$(MOVE) $(TARGET) ../libs/ 


Makefile: sstDxf02Lib.pro /usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		sstDxf02Lib.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile sstDxf02Lib.pro
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf:
sstDxf02Lib.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile sstDxf02Lib.pro

qmake_all: FORCE


all: Makefile ../libs/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../libs/$(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

sstDxf02Arc.o: sstDxf02Arc.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Arc.o sstDxf02Arc.cpp

sstDxf02Base.o: sstDxf02Base.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Base.o sstDxf02Base.cpp

sstDxf02Insert.o: sstDxf02Insert.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Insert.o sstDxf02Insert.cpp

sstDxf02Read.o: sstDxf02Read.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Read.o sstDxf02Read.cpp

sstDxf02Block.o: sstDxf02Block.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Block.o sstDxf02Block.cpp

sstDxf02Layer.o: sstDxf02Layer.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Layer.o sstDxf02Layer.cpp

sstDxf02Database.o: sstDxf02Database.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Database.o sstDxf02Database.cpp

sstDxf02EntityType.o: sstDxf02EntityType.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02EntityType.o sstDxf02EntityType.cpp

sstDxf02Write.o: sstDxf02Write.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Write.o sstDxf02Write.cpp

sstDxf02Main.o: sstDxf02Main.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Main.o sstDxf02Main.cpp

sstDxf02Vertex.o: sstDxf02Vertex.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Vertex.o sstDxf02Vertex.cpp

sstDxf02Polyline.o: sstDxf02Polyline.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Polyline.o sstDxf02Polyline.cpp

sstDxf02Hatch.o: sstDxf02Hatch.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Hatch.o sstDxf02Hatch.cpp

sstDxf02HatchLoop.o: sstDxf02HatchLoop.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02HatchLoop.o sstDxf02HatchLoop.cpp

sstDxf02HatchEdge.o: sstDxf02HatchEdge.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02HatchEdge.o sstDxf02HatchEdge.cpp

sstDxf02LType.o: sstDxf02LType.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02LType.o sstDxf02LType.cpp

sstDxf02Circle.o: sstDxf02Circle.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Circle.o sstDxf02Circle.cpp

sstDxf02MText.o: sstDxf02MText.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02MText.o sstDxf02MText.cpp

sstDxf02Text.o: sstDxf02Text.cpp ../dxflib/Header/dl_dxf.h \
		../dxflib/Header/dl_global.h \
		../dxflib/Header/dl_attributes.h \
		../dxflib/Header/dl_codes.h \
		../dxflib/Header/dl_entities.h \
		../dxflib/Header/dl_writer_ascii.h \
		../dxflib/Header/dl_writer.h \
		../dxflib/Header/dl_creationadapter.h \
		../dxflib/Header/dl_creationinterface.h \
		../dxflib/Header/dl_extrusion.h \
		../sstLibreCAD2Lib/Header/rs_vector.h \
		../sstLibreCAD2Lib/Header/rs.h \
		../sst_str01_lib/Header/sstStr01Lib.h \
		../sst_misc01_lib/Header/sstMisc01Lib.h \
		../sst_rec04_lib/Header/sstRec04Lib.h \
		Header/sstDxf02Lib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sstDxf02Text.o sstDxf02Text.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

